import { describe, expect, it } from 'vitest'
import { encodeQr, type QrEcc } from './qr'
import fixtures from './qr.fixtures.json'

const flat = (matrix: readonly (readonly boolean[])[]) =>
  matrix.map((row) => row.map((dark) => (dark ? '1' : '0')).join('')).join('')

describe('own QR encoder (ISO/IEC 18004)', () => {
  // Matrices generated by a reference implementation (python-qrcode 7.4.2, byte mode).
  it.each(fixtures)('matches the reference for "$text" ($ecc, mask $mask)', (fixture) => {
    expect(flat(encodeQr(fixture.text, { ecc: fixture.ecc as QrEcc, mask: fixture.mask }))).toBe(
      fixture.matrix,
    )
  })

  it('picks the smallest version and a valid mask automatically', () => {
    const matrix = encodeQr('NL:0123456789')
    expect(matrix).toHaveLength(21)
    // Finder pattern corners and the always-dark module.
    expect(matrix[0]!.slice(0, 7).every(Boolean)).toBe(true)
    expect(matrix[21 - 8]![8]).toBe(true)
  })

  it('refuses texts beyond version 10', () => {
    expect(() => encodeQr('x'.repeat(400))).toThrow('qr_too_long')
  })
})
